// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: proto/student.proto

package sutdent

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 发送请求
type SendParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 发送的参数字段
	// 参数类型 参数名 标识号(不可重复)
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // 要请求的地址
	Method  string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`   // 请求方式
}

func (x *SendParam) Reset() {
	*x = SendParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_student_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendParam) ProtoMessage() {}

func (x *SendParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendParam.ProtoReflect.Descriptor instead.
func (*SendParam) Descriptor() ([]byte, []int) {
	return file_proto_student_proto_rawDescGZIP(), []int{0}
}

func (x *SendParam) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SendParam) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// 返回响应
type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 接收的参数字段
	// 参数类型 参数名 标识号
	HttpCode int32  `protobuf:"varint,1,opt,name=httpCode,proto3" json:"httpCode,omitempty"` // http状态码
	Response string `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`  // 返回体
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_student_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_student_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetHttpCode() int32 {
	if x != nil {
		return x.HttpCode
	}
	return 0
}

func (x *GetResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_proto_student_proto protoreflect.FileDescriptor

var file_proto_student_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x75, 0x74, 0x64, 0x65, 0x6e, 0x74, 0x22, 0x3d,
	0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x45, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x68, 0x74, 0x74, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x68, 0x74, 0x74, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x44, 0x0a, 0x09, 0x47, 0x6f, 0x53, 0x75, 0x74, 0x64, 0x65, 0x6e,
	0x74, 0x12, 0x37, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x75, 0x74, 0x64, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x12, 0x2e, 0x73, 0x75, 0x74, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x1a, 0x14, 0x2e, 0x73, 0x75, 0x74, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_student_proto_rawDescOnce sync.Once
	file_proto_student_proto_rawDescData = file_proto_student_proto_rawDesc
)

func file_proto_student_proto_rawDescGZIP() []byte {
	file_proto_student_proto_rawDescOnce.Do(func() {
		file_proto_student_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_student_proto_rawDescData)
	})
	return file_proto_student_proto_rawDescData
}

var file_proto_student_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_student_proto_goTypes = []interface{}{
	(*SendParam)(nil),   // 0: sutdent.SendParam
	(*GetResponse)(nil), // 1: sutdent.GetResponse
}
var file_proto_student_proto_depIdxs = []int32{
	0, // 0: sutdent.GoSutdent.GetSutdents:input_type -> sutdent.SendParam
	1, // 1: sutdent.GoSutdent.GetSutdents:output_type -> sutdent.GetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_student_proto_init() }
func file_proto_student_proto_init() {
	if File_proto_student_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_student_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_student_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_student_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_student_proto_goTypes,
		DependencyIndexes: file_proto_student_proto_depIdxs,
		MessageInfos:      file_proto_student_proto_msgTypes,
	}.Build()
	File_proto_student_proto = out.File
	file_proto_student_proto_rawDesc = nil
	file_proto_student_proto_goTypes = nil
	file_proto_student_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GoSutdentClient is the client API for GoSutdent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoSutdentClient interface {
	// rpc请求 请求的函数 (发送请求参数) returns (返回响应的参数)
	GetSutdents(ctx context.Context, in *SendParam, opts ...grpc.CallOption) (*GetResponse, error)
}

type goSutdentClient struct {
	cc grpc.ClientConnInterface
}

func NewGoSutdentClient(cc grpc.ClientConnInterface) GoSutdentClient {
	return &goSutdentClient{cc}
}

func (c *goSutdentClient) GetSutdents(ctx context.Context, in *SendParam, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/sutdent.GoSutdent/GetSutdents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoSutdentServer is the server API for GoSutdent service.
type GoSutdentServer interface {
	// rpc请求 请求的函数 (发送请求参数) returns (返回响应的参数)
	GetSutdents(context.Context, *SendParam) (*GetResponse, error)
}

// UnimplementedGoSutdentServer can be embedded to have forward compatible implementations.
type UnimplementedGoSutdentServer struct {
}

func (*UnimplementedGoSutdentServer) GetSutdents(context.Context, *SendParam) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSutdents not implemented")
}

func RegisterGoSutdentServer(s *grpc.Server, srv GoSutdentServer) {
	s.RegisterService(&_GoSutdent_serviceDesc, srv)
}

func _GoSutdent_GetSutdents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSutdentServer).GetSutdents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sutdent.GoSutdent/GetSutdents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSutdentServer).GetSutdents(ctx, req.(*SendParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoSutdent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sutdent.GoSutdent",
	HandlerType: (*GoSutdentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSutdents",
			Handler:    _GoSutdent_GetSutdents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/student.proto",
}
